version: 2
updates:
  - package-ecosystem: maven
    directory: "/backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/backend/services/identity-service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/backend/services/lead-service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/backend/services/ai-service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/backend/services/customer-service"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/infrastructure/api-gateway"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/infrastructure/service-registry"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
