pipeline {
    agent any
    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Build') {
            steps {
                sh './mvnw clean verify -B'
            }
        }
        stage('Docker Build') {
            when { branch 'main' }
            steps {
                sh './scripts/docker-build-all.sh'
            }
        }
    }
    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
