server:
  port: 8085

spring:
  application:
    name: catalog-service
  profiles:
    default: local
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:platform/application-observability.yml
      - optional:classpath:platform/application-cache.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: aisales
    password: ${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:aisales}}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092

aisales:
  security:
    use-platform-defaults: true
  events:
    default-topic: aisales-events
    outbox:
      enabled: true
    inbox:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
