package com.aisales.common.contracts.workflow;

public enum WorkflowTriggerType {
    LEAD_CREATED,
    LEAD_QUALIFIED,
    OPPORTUNITY_CREATED,
    CONVERSATION_STARTED,
    MESSAGE_RECEIVED,
    MESSAGE_SENT,
    CUSTOMER_CONVERTED,
    AI_QUALIFICATION_COMPLETED,
    CATALOG_RECOMMENDATION_GENERATED,
    CONVERSATION_CLOSED,
    MANUAL
}
